"""nulls_and_new_column

Revision ID: 6ef68d97dbd6
Revises: 82b4a27c811f
Create Date: 2026-02-28 19:03:27.146932

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '6ef68d97dbd6'
down_revision: Union[str, Sequence[str], None] = '82b4a27c811f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('preprocessed_emails', sa.Column('short_question', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.alter_column('preprocessed_emails', 'fio',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('preprocessed_emails', 'object',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('preprocessed_emails', 'object_number',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('preprocessed_emails', 'object_type',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('preprocessed_emails', 'phone_number',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('preprocessed_emails', 'phone_number',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('preprocessed_emails', 'object_type',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('preprocessed_emails', 'object_number',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('preprocessed_emails', 'object',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('preprocessed_emails', 'fio',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('preprocessed_emails', 'short_question')
    # ### end Alembic commands ###
