import type { Place } from './types';

/**
 * Захардкоженный демо-датасет для MVP. После подключения Places API
 * (Яндекс / наш бэк) этот список заменяется на запрос `GET /places`.
 */
export const demoPlaces: Place[] = [
  {
    id: 'eltsin-center',
    name: 'Ельцин Центр',
    description:
      'Современное пространство с музеем, галереями и кофейней в самом центре.',
    categories: ['history', 'art'],
    priceMin: 0,
    priceMax: 400,
    durationHours: 2,
    lat: 56.8441,
    lng: 60.5891,
    address: 'ул. Бориса Ельцина, 3',
    accessibility: ['wheelchair', 'ramps', 'avoid_stairs'],
  },
  {
    id: 'plotinka',
    name: 'Плотинка',
    description:
      'Историческое сердце города и парк на Исети — прогулки, стрит-арт, виды.',
    categories: ['history', 'nature', 'relax'],
    priceMin: 0,
    priceMax: 0,
    durationHours: 1,
    lat: 56.8388,
    lng: 60.6120,
    address: 'пл. Труда',
    accessibility: ['wheelchair', 'ramps', 'avoid_stairs', 'none'],
  },
  {
    id: 'opera',
    name: 'Театр оперы и балета',
    description:
      'Главная классическая сцена Урала — вечерние спектакли и экскурсии днём.',
    categories: ['music', 'art'],
    priceMin: 500,
    priceMax: 3500,
    durationHours: 3,
    lat: 56.8388,
    lng: 60.6022,
    address: 'пр. Ленина, 46А',
    accessibility: ['wheelchair', 'ramps'],
  },
  {
    id: 'sevastyanov',
    name: 'Дом Севастьянова',
    description: 'Нарядная резиденция в стиле псевдоготики, экскурсии по записи.',
    categories: ['history', 'art'],
    priceMin: 350,
    priceMax: 600,
    durationHours: 1,
    lat: 56.8420,
    lng: 60.6099,
    address: 'пр. Ленина, 35',
    accessibility: [],
  },
  {
    id: 'kharitonov-park',
    name: 'Харитоновский сад',
    description: 'Тенистый парк с прудом у дома Расторгуевых-Харитоновых.',
    categories: ['nature', 'relax', 'history'],
    priceMin: 0,
    priceMax: 0,
    durationHours: 1,
    lat: 56.8428,
    lng: 60.6125,
    address: 'ул. Карла Либкнехта, 44',
    accessibility: ['wheelchair', 'avoid_stairs', 'none'],
  },
  {
    id: 'mayakovsky-park',
    name: 'ЦПКиО им. Маяковского',
    description:
      'Большой парк с аттракционами, прокатами и набережной — отдых на полдня.',
    categories: ['nature', 'relax'],
    priceMin: 0,
    priceMax: 800,
    durationHours: 4,
    lat: 56.8160,
    lng: 60.6295,
    address: 'ул. Мичурина, 230',
    accessibility: ['wheelchair', 'ramps', 'avoid_stairs', 'none'],
  },
  {
    id: 'simple-coffee',
    name: 'Simple Coffee',
    description: 'Местная сеть спешелти-кофейни с фильтрами и десертами.',
    categories: ['coffee', 'relax'],
    priceMin: 200,
    priceMax: 600,
    durationHours: 1,
    lat: 56.8389,
    lng: 60.6057,
    address: 'ул. 8 Марта, 8Д',
    accessibility: ['wheelchair', 'avoid_stairs'],
  },
  {
    id: 'engels-coffee',
    name: 'Engels Coffee',
    description: 'Уютная кофейня с сезонными напитками и зимним садом.',
    categories: ['coffee', 'relax'],
    priceMin: 250,
    priceMax: 700,
    durationHours: 1,
    lat: 56.8409,
    lng: 60.6084,
    address: 'ул. Энгельса, 9',
    accessibility: ['wheelchair', 'avoid_stairs'],
  },
  {
    id: 'geology-museum',
    name: 'Уральский геологический музей',
    description: 'Коллекция уральских самоцветов и минералов, хорошо с гидом.',
    categories: ['history', 'art'],
    priceMin: 200,
    priceMax: 400,
    durationHours: 2,
    lat: 56.8394,
    lng: 60.6141,
    address: 'ул. Хохрякова, 85',
    accessibility: ['hearing'],
  },
  {
    id: 'literary-quarter',
    name: 'Литературный квартал',
    description:
      'Пешеходная зона с домами-музеями уральских писателей и деревянными улочками.',
    categories: ['history', 'art', 'relax'],
    priceMin: 0,
    priceMax: 300,
    durationHours: 2,
    lat: 56.8420,
    lng: 60.6155,
    address: 'ул. Пролетарская, 10',
    accessibility: ['avoid_stairs'],
  },
];

export const EKATERINBURG_CENTER = { lat: 56.8389, lng: 60.6057 } as const;
